### ISSUE TITLE
iteration counter?

### ISSUE THREAD

**Issue by hallalujeh** [Lakshit-Karsoliya/Subdora#3]
what is the iteration counter about? can we set it to any value and is it perhaps related to security, like the higher the iteration count would lead to higher the protection?

**Comment by Lakshit-Karsoliya** [comment]
An iteration counter only tracks how many times a file has been executed. For example, if you set it to 5, you can only run the myst file 5 times. If you try to run it more than 5 times, all logic inside the myst file will be erased.

**Comment by hallalujeh** [comment]
> An iteration counter only tracks how many times a file has been executed. For example, if you set it to 5, you can only run the myst file 5 times. If you try to run it more than 5 times, all logic inside the myst file will be erased.

oh i see thanks for the insight
